---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: concession-kiosk-app
  labels:
    app: backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: backend
  template:
    metadata:
      labels:
        deployment: backend
    spec:
      containers:
        - name: backend
          image: quay.io/julin/concession-kiosk-app:1.0
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: MONGODB_URL
              value: 'mongodb://user1:password123@mongodb.concession-kiosk-db.svc.cluster.local/sampledb'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
