---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-storage
  labels:
    role: mongodb
  namespace: concession-kiosk-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
