---
apiVersion: v1
kind: LimitRange
metadata:
  name: concession-kiosk-resource-limits
spec:
  limits:
  - default:
      cpu: 500m
      memory: 1536Mi
    defaultRequest:
      cpu: 50m
      memory: 256Mi
    max:
      cpu: "4"
      memory: 6Gi
    type: Container
  - max:
      cpu: "4"
      memory: 12Gi
    type: Pod
